# Generated by Django 6.0 on 2025-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pfp',
            field=models.ImageField(blank=True, default='../../pfp/pfp.png', max_length=128, null=True, upload_to='images/'),
        ),
    ]
