# Generated by Django 6.0 on 2025-12-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pfp',
            field=models.ImageField(default='/media/images/defaultPfp.png', max_length=128, upload_to='images/'),
        ),
    ]
